# System-wide configuration
system:
  name: "Distributed Web Scraping System"
  version: "1.0.0"
  environment: "production"

# Redis configuration
redis:
  host: "localhost"
  port: 6379
  db: 0
  timeout: 5
  max_connections: 100

# Database configuration
databases:
  mongo:
    uri: "mongodb://localhost:27017/"
    database: "scraping_data"
    timeout: 5000
  postgres:
    host: "localhost"
    port: 5432
    database: "scraping_data"
    user: "scraper"
    password: "securepassword"
    pool_size: 10

# Scrapy settings
scrapy:
  concurrent_requests: 100
  download_delay: 0.25
  retry_enabled: true
  retry_times: 3
  retry_http_codes: [500, 502, 503, 504, 408]
  httpcache_enabled: false

# Monitoring settings
monitoring:
  prometheus:
    enabled: true
    port: 9090
  grafana:
    enabled: true
    port: 3000
  alert_thresholds:
    error_rate: 0.1
    response_time: 5.0
    throughput: 10

# Security settings
security:
  encryption:
    enabled: true
    algorithm: "AES-256-CBC"
  access_control:
    enabled: true
    roles:
      - admin
      - scraper
      - viewer
